export const CLIENT_LIKERT_ITEMS = [
  'Tengo claras mis metas de ahorro, a corto, mediano y largo plazo.',
  'Gasto únicamente en lo necesario.',
  'Tengo un plan para incrementar mis ingresos en el corto plazo.',
  'Estoy ahorrando para un objetivo de largo plazo.',
  'Cuando se trata de dinero, tomo decisiones fría, racional y concienzudamente.',
  'Invierto mi dinero en opciones que son convenientes para mí.',
  'Nunca dejo ir una buena oportunidad para ganar un dinero extra.',
  'Siempre guardo algo de lo que gano.',
  'Me implico activamente en crear oportunidades que me generen ingresos.',
  'Realizo inversiones que me producen cada vez mejores rendimientos.',
  'Mis deudas están perfectamente controladas.',
  'Me administro de una forma que siempre me queda algo para ahorrar.',
  'Solo compro lo realmente necesario.',
  'Al tomar decisiones de dinero me aseguro de obtener siempre el máximo rendimiento.',
  'Me aseguro de sacar el mayor provecho a los recursos que tengo disponibles.',
  'Estoy preparado para afrontar un imprevisto sin desestabilizar mis finanzas.',
  'De mis deudas siempre pago más del saldo mínimo.',
  'Actualmente estoy invirtiendo mi dinero.',
  'Compro cosas solo cuando tengo la certeza de que las podré pagar.',
  'Constantemente estoy ideando formas de ganar dinero.',
  'Acostumbro seguir un presupuesto de gasto.',
  'Sacrifico parte de mis ganancias para volverlas a invertir.',
  'Facilito las cosas para que el dinero venga a mí.',
  'Nunca gasto más de lo que gano.',
  'Acostumbro adelantar pagos para acabar más rápido con mis compromisos.',
] as const;

export const LIKERT_LABELS = [
  'Falso completamente',
  'Moderadamente falso',
  'Ni falso ni verdadero',
  'Moderadamente verdadero',
  'Verdadero completamente',
] as const;
